Repository SnowballXueQiu/RescueMe, pull requests merged in 2023-09, with the labels that each got.

#2 feat: minify bundle
  content/index.md
  nuxt.config.ts
  package.json
  pages/[...slug].vue
  pnpm-lock.yaml
  scripts/useAllRouter.ts
Labels: enhancement

#1 feat: refinement of layout
  content/index.md
  pages/[...slug].vue
Labels: enhancement

#4 feat: refinement footer layout
  content/index.md
  nuxt.config.ts
  pages/[...slug].vue
Labels: enhancement

#6 fix: fix animation wrong
  assets/css/main.css
  pages/[...slug].vue
Labels: bug

#7 feat: dark scroll bar
  assets/css/main.css
Labels: enhancement

#8 security: codeql
  .github/workflows/codeql.yml
Labels: enhancement

#10 Create SECURITY.md
  SECURITY.md
Labels: documentation

#11 fix: animation
  package.json
  pages/[...slug].vue
Labels: bug

#12 optimize: seo
  app.vue
  pages/[...slug].vue
Labels: enhancement

#13 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#14 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#16 feat: menu
  app.vue
  components/git-meta.vue
  components/logo.vue
  nuxt.config.ts
  package.json
  pages/[...slug].vue
  pages/index.vue
  pages/posts/[...slug].vue
  scripts/useAllRouter.ts
  scripts/usePreRenderRoute.ts
  server/tsconfig.json
Labels: enhancement
