Repository SnowballXueQiu/RescueMe, pull requests merged in 2023-10, with the labels that each got.

#20 doc: add gitattributes
  .gitattributes
Labels: documentation

#22 fix: the issue of incorrect navigation
  nuxt.config.ts
  pages/index.vue
  pages/posts/[...slug].vue
  tailwind.config.js
Labels: enhancement

#23 fix: navigation error
  nuxt.config.ts
  pages/index.vue
  pages/posts/[...slug].vue
Labels: bug

#24 feat: scroll-bar
  nuxt.config.ts
Labels: enhancement

#25 feat: add post enter animation
  nuxt.config.ts
  pages/index.vue
  pages/posts/[...slug].vue
Labels: enhancement
